apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ridego.fullname" . }}-frontend
  labels: {{- include "ridego.labels" . | nindent 4 }}
data:
  CAR_URL: http://{{ include "ridego.fullname" . }}-ride:5001
  BOOKING_URL: http://{{ include "ridego.fullname" . }}-booking:5002
  CONTACT_URL: http://{{ include "ridego.fullname" . }}-contact:5003
